before:
  hooks:
    - go mod download
builds:
  - env:
      - CGO_ENABLED=0
  main: ./main.go
  goos:
    - darwin
    - linux
    - windows
  goarch:
    - 386
    - amd64
    - arm64
    - arm
  goarm:
    - 5
    - 6
    - 7
  ignore:
    - goos: windows
      goarch: 386
    - goos: darwin
      goarch: 386
  ldflags:
    - "-X 'main.version={{ .Tag }}'"
archives:
  - replacements:
    name_template: "{{ .Binary }}-{{ .Os }}-{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}"
    format_overrides:
      - goos: windows
        format: zip
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
