apiPort: 0
bindings:
- name: target-1
  properties: {}
  source:
    kind: kubemq.queue
    properties:
      address: kubemq-cluster-grpc:50000
      channel: asd
  target:
    kind: echo
    properties: {}
logLevel: ""
