bindings:
  - name: target-1
    properties:
      log_level: info
    source:
      kind: kubemq.queue
      properties:
        address: localhost:50000
        channel: queue.s3.up
        sources: 5
        batch_size: 10
    target:
      kind: aws.s3
      properties:
        aws_key: your aws key
        aws_secret_key: your aws secrete
        region: your zone
        token: ""
  - name: target-2
    properties:
      log_level: info
    source:
      kind: kubemq.queue
      properties:
        address: localhost:50000
        channel: queue.s3.down
        sources: 5
        batch_size: 10
    target:
      kind: storage.filesystem
      name: target-filesystem
      properties:
        base_path: "d:/sync/down"
