apiPort: 8090
bindings:
- name: fs
  source:
    kind: kubemq.queue
    properties:
      address: localhost:50000
      channel: queue.fs
  target:
    kind: storage.filesystem
    properties:
      base_path: "./test-fs"
  properties: {}
