apiPort: 0
bindings:
  - name: target-1
    properties:
      log_level: debug
    source:
      kind: kubemq.query
      properties:
        address: localhost:50000
        channel: e2
    target:
      kind: echo
  #bindings:
  - name: sync.down
    properties:
      log_level: info
    source:
      kind: kubemq.queue-stream
      properties:
        address: localhost:50000
        channel: queue.s3.down
        sources: 5
    target:
      kind: storage.filesystem
      properties:
        base_path: "d:/sync/down"
  - name: sync.up
    properties:
      log_level: info
    source:
      kind: kubemq.queue-stream
      properties:
        address: localhost:50000
        channel: queue.s3.up
        sources: 5
    target:
      kind: aws.s3
      name: aws-s3
      properties:
        region: "us-east-1"
        token: ""
#logLevel: "debug"
