apiPort: 8081
bindings:
- name: target-1
  properties:
    log_level: info
  source:
    kind: kubemq.query
    properties:
      address: localhost:50000
      channel: echo
  target:
    kind: echo
    properties: {}
logLevel: ""
