apiPort: 8090
bindings:
- name: echo1
  source:
    kind: kubemq.query
    properties:
      address: localhost:50000
      channel: query.echo
  target:
    kind: echo
    properties: {}
  properties: {}
- name: echo2
  source:
    kind: kubemq.query
    properties:
      address: localhost:50000
      channel: query.echo
  target:
    kind: echo
    properties: {}
  properties: {}
