bindings:
- name: hdfs
  source:
    kind: kubemq.query
    properties:
      address: localhost:50000
      channel: query.hdfs
  target:
    kind: storage.hdfs
    properties:
      address: localhost:9000
      user: test_user
  properties: {}
