apiPort: 8090
bindings:
- name: fs
  source:
    kind: kubemq.queue
    properties:
      address: localhost:50000
      channel: queue.fs
      sources: "5"
  target:
    kind: storage.minio
    properties:
      access_key_id: minio
      endpoint: localhost:9000
      secret_access_key: minio123
      use_ssl: "false"
  properties: {}
- name: http
  source:
    kind: kubemq.queue
    properties:
      address: localhost:50000
      channel: queue.http
      max_requeue: "0"
  target:
    kind: echo
    properties: {}
  properties: {}
