apiPort: 0
bindings:
  - name: target-1
    properties:
      log_level: debug
    source:
      kind: kubemq.query
      properties:
        address: localhost:50000
        channel: e2
    target:
      kind: echo
  #bindings:
  - name: kubemq-query-filesystem
    properties:
      log_level: info
    source:
      kind: kubemq.queue
      properties:
        address: localhost:50000
        channel: queue.minio
    target:
      kind: storage.filesystem
      properties:
        base_path: "d:/sync"
#logLevel: "debug"
