bindings:
- name: consulkv
  source:
    kind: kubemq.query
    properties:
      address: localhost:50000
      channel: query.consulkv
  target:
    kind: stores.consulkv
    properties:
      address: localhost:8500
  properties: {}
