version: "2.1"

services:
  namenode:
    build: ./namenode
    container_name: namenode
    environment:
      - CLUSTER_NAME=test
    env_file:
      - ./hadoop.env
    ports:
      - "9870:9870"
      - "9000:9000"
  
  resourcemanager:
    build: ./resourcemanager
    container_name: resourcemanager
    restart: on-failure
    depends_on:
      - namenode
      - datanode1
      - datanode2
      - datanode3
    env_file:
      - ./hadoop.env
    ports:
      - "8089:8088"
  
  historyserver:
    build: ./historyserver
    container_name: historyserver
    depends_on:
      - namenode
      - datanode1
      - datanode2
    env_file:
      - ./hadoop.env
    ports:
      - "8188:8188"
  
  nodemanager1:
    build: ./nodemanager
    container_name: nodemanager1
    depends_on:
      - namenode
      - datanode1
      - datanode2
    env_file:
      - ./hadoop.env
    ports:
      - "8042:8042"
  
  datanode1:
    build: ./datanode
    container_name: datanode1
    depends_on:
      - namenode
    env_file:
      - ./hadoop.env
  
  datanode2:
    build: ./datanode
    container_name: datanode2
    depends_on:
      - namenode
    env_file:
      - ./hadoop.env
  
  datanode3:
    build: ./datanode
    container_name: datanode3
    depends_on:
      - namenode
    env_file:
      - ./hadoop.env
