bindings:
  - name: kubemq-query-singlestore
    source:
      kind: kubemq.query
      name: kubemq-query
      properties:
        address: "kubemq-cluster:50000"
        client_id: "kubemq-query-singlestore-connector"
        auth_token: ""
        channel: "query.singlestore"
        group:   ""
        auto_reconnect: "true"
        reconnect_interval_seconds: "1"
        max_reconnects: "0"
    target:
      kind: stores.singlestore
      name: stores-singlestore
      properties:
        connection: "root:root@(localhost:3306)/test?charset=utf8&parseTime=True&loc=Local"
        max_idle_connections: "10"
        max_open_connections: "100"
        connection_max_lifetime_seconds: "3600"