name: golangci-lint
on:
  push:
    tags:
      - '*'
    branches:
      - master
  pull_request:
jobs:
  golangci:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: install-ibmmq-sdk
        run: sh ./ci/ibmmq-sdk/install-linux.sh
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v2
        with:
          # Required: the version of golangci-lint is required and must be specified without patch version: we always use the latest patch version.
          version: v1.39

          # Optional: working directory, useful for monorepos
          # working-directory: somedir

          # Optional: golangci-lint command line arguments.
          args: --issues-exit-code=0 --disable gocritic --enable misspell --disable gosec --timeout=30m
